# Auto-generated by compose2nix.
{
  pkgs,
  lib,
  config,
  ...
}: {
  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll =
      if !config.networking.nftables.enable
      then "podman+"
      else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [53];
  };

  sops.secrets."zurg.yml" = {
    sopsFile = ./config.yml;
    format = "yaml";
    key = "";
    restartUnits = ["podman-zurg.service"];
  };

  # Containers
  virtualisation.oci-containers.containers."rclone" = {
    image = "rclone/rclone:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Europe/Berlin";
    };
    volumes = [
      "${./rclone.conf}:/config/rclone/rclone.conf:rw"
      "/mnt/zurg:/data:rw,rshared"
    ];
    cmd = ["mount" "zurg:" "/data" "--allow-other" "--allow-non-empty" "--dir-cache-time" "10s" "--vfs-cache-mode" "full"];
    dependsOn = [
      "zurg"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cap-add=SYS_ADMIN"
      "--device=/dev/fuse:/dev/fuse:rwm"
      "--network-alias=rclone"
      "--network=zurg_default"
      "--security-opt=apparmor:unconfined"
    ];
  };
  systemd.services."podman-rclone" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-zurg_default.service"
    ];
    requires = [
      "podman-network-zurg_default.service"
    ];
    partOf = [
      "podman-compose-zurg-root.target"
    ];
    wantedBy = [
      "podman-compose-zurg-root.target"
    ];
  };

  virtualisation.oci-containers.containers."zurg" = {
    image = "ghcr.io/debridmediamanager/zurg-testing:latest";
    volumes = [
      "${config.sops.secrets."zurg.yml".path}:/app/config.yml:rw"
      "${../../scripts/jellyfin_update.sh}:/app/jellyfin_update.sh:ro"
      "zurg_zurgdata:/app/data:rw"
    ];
    ports = [
      "9999:9999/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=zurg"
      "--network=zurg_default"
      "--network=jellyfin_default"
    ];
  };
  systemd.services."podman-zurg" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-zurg_default.service"
      "podman-network-jellyfin_default.service"
      "podman-volume-zurg_zurgdata.service"
    ];
    requires = [
      "podman-network-zurg_default.service"
      "podman-network-jellyfin_default.service"
      "podman-volume-zurg_zurgdata.service"
    ];
    partOf = [
      "podman-compose-zurg-root.target"
    ];
    wantedBy = [
      "podman-compose-zurg-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-zurg_default" = {
    path = [pkgs.podman];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f zurg_default";
    };
    script = ''
      podman network inspect zurg_default || podman network create zurg_default
    '';
    partOf = ["podman-compose-zurg-root.target"];
    wantedBy = ["podman-compose-zurg-root.target"];
  };

  # Volumes
  systemd.services."podman-volume-zurg_zurgdata" = {
    path = [pkgs.podman];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect zurg_zurgdata || podman volume create zurg_zurgdata
    '';
    partOf = ["podman-compose-zurg-root.target"];
    wantedBy = ["podman-compose-zurg-root.target"];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-zurg-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
