# Auto-generated using compose2nix v0.3.2-pre.
{ pkgs, lib, config, ... }:

{
  # Runtime
  myFolders = {
    minecraft-server = {
      path = "/home/ubuntu/minecraft";
      owner = "ubuntu";
      group = "users";
      mode = "0755";
    };
  };


  sops.secrets."minecraft.env" = {
    sopsFile = ./minecraft.env;
    format = "dotenv";
    key = "";
    restartUnits = ["podman-minecraft-server-mc.service"];
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."minecraft-server-mc" = {
    image = "itzg/minecraft-server";
    environment = {
      "EULA" = "TRUE";
    };
    volumes = [
      "/home/ubuntu/minecraft:/data:rw"
    ];
    ports = [
      "25565:25565/tcp"
    ];
    labels = {
      "traefik.enable" = "true";
      "traefik.http.routers.minecraft.entrypoints" = "minecraft";
      "traefik.http.routers.minecraft.rule" = "Host(`mc.kuipr.de`)";
      "traefik.http.services.minecraft.loadbalancer.server.port" = "25565";
    };
    environmentFiles = [
      "${config.sops.secrets."minecraft.env".path}"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=mc"
      "--network=minecraft-server_default"
    ];
  };
  systemd.services."podman-minecraft-server-mc" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-minecraft-server_default.service"
    ];
    requires = [
      "podman-network-minecraft-server_default.service"
    ];
    partOf = [
      "podman-compose-minecraft-server-root.target"
    ];
    wantedBy = [
      "podman-compose-minecraft-server-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-minecraft-server_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f minecraft-server_default";
    };
    script = ''
      podman network inspect minecraft-server_default || podman network create minecraft-server_default
    '';
    partOf = [ "podman-compose-minecraft-server-root.target" ];
    wantedBy = [ "podman-compose-minecraft-server-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-minecraft-server-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
