name: navidrome
services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    volumes:
      - "/home/ubuntu/navidrome:/data"
      - "/mnt/data/media/music:/music:ro"
