global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/alert-rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: /metrics
    scrape_interval: 30s

  # Loki metrics
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
    metrics_path: /metrics
    scrape_interval: 30s

  # Alertmanager metrics
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
    metrics_path: /metrics
    scrape_interval: 30s

  # Traefik metrics (if enabled)
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    metrics_path: /metrics
    scrape_interval: 30s

  # HAProxy metrics
  - job_name: 'haproxy'
    static_configs:
      - targets: ['host.docker.internal:8405']
    metrics_path: /metrics
    scrape_interval: 15s

  # Fail2ban metrics
  - job_name: 'fail2ban'
    static_configs:
      - targets: ['fail2ban-exporter:9191']
    scrape_interval: 30s

    # Podman metrics
  - job_name: 'podman'
    static_configs:
      - targets: [ 'podman-exporter:9882']
    scrape_interval: 30s


  # qBittorrent metrics
  - job_name: 'qbittorrent'
    static_configs:
      - targets: ['qbit_exporter:8000']
    metrics_path: /metrics
    scrape_interval: 30s

  # Authelia metrics
  - job_name: 'authelia'
    static_configs:
      - targets: ['authelia:9959']
    scrape_interval: 30s
    metrics_path: /metrics

  # Anubis metrics
  - job_name: 'anubis'
    static_configs:
      - targets: ['anubis:9093']
    scrape_interval: 30s
    metrics_path: /metrics
