name: obsidian-share-notes
services:
  notesx-server:
    image: ghcr.io/note-sx/server:latest
    container_name: notesx-server
    restart: always
    # ports:
    #  - "3000:3000"
    networks:
      - default
      - proxy
    environment:
      - BASE_WEB_URL=https://notes.kuipr.de
      - HASH_SALT=dkoawdaw9fdjkafhus
      - MAXIMUM_UPLOAD_SIZE_MB=10
    volumes:
      - ./db:/notesx/db:Z
      - ./userfiles:/notesx/userfiles:Z
    healthcheck:
      test: (wget -qO - http://localhost:3000/v1/ping | grep -q ok) || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.notesx-server.rule=Host(`notes.kuipr.de`)"
      - "traefik.http.routers.notesx-server.entrypoints=websecure"
      - "traefik.http.routers.notesx-server.tls.certresolver=myresolver"
      - "traefik.http.services.notesx-server.loadbalancer.server.port=3000"

networks:
  default: {}
  proxy:
    external: true
