name: traefik
services:
  traefik:
    image: "traefik:v3.3"
    container_name: "traefik"
    command:
      - "--api"
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--accesslog.filepath=/logs/access.log"
      - "--accesslog.bufferingsize=100"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.file.directory=/config"
      - "--providers.file.watch=true"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=proxy"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      # DNS Challenge with BunnyDNS configuration
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=bunny"
      - "--certificatesresolvers.myresolver.acme.email=daniel.inama02@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      # Optional: Use Buypass instead of Let's Encrypt (uncomment if needed)
      # - "--certificatesresolvers.myresolver.acme.caServer=https://api.buypass.no/acme/directory"
      - "--serversTransport.insecureSkipVerify=true"
    ports:
      - "8081:80"
      - "8443:443"
      - "8181:8080"
    volumes:
      - "/var/lib/traefik/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/var/lib/traefik/logs:/logs"
      - "/var/lib/traefik/config:/config"
    networks:
      - proxy
    restart: always

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.kuipr.de`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    name: proxy
