##############################################
#                                            #
#              Authelia Config               #
#                                            #
##############################################
# The host and port to listen on
server:
  host: 0.0.0.0
  port: 9091

# Default redirection URL
default_redirection_url: https://kuipr.de

# TOTP settings
totp:
  issuer: kuipr.de
  period: 30
  skew: 1

# Authentication backend
authentication_backend:
  file:
    path: /config/users_database.yaml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64
  ldap:
    address: 'ldap://127.0.0.1'
    implementation: 'custom'
    timeout: '5s'
    start_tls: false
    tls:
      server_name: 'ldap.kuipr.de'
      skip_verify: true
      minimum_version: 'TLS1.2'
      maximum_version: 'TLS1.3'
      # certificate_chain: |
      #   -----BEGIN CERTIFICATE-----
      #   ...
      #   -----END CERTIFICATE-----
      #   -----BEGIN CERTIFICATE-----
      #   ...
      #   -----END CERTIFICATE-----
      # private_key: |
      #   -----BEGIN RSA PRIVATE KEY-----
      #   ...
      #   -----END RSA PRIVATE KEY-----
    pooling:
      enable: false
      count: 5
      retries: 2
      timeout: '10 seconds'
    base_dn: 'DC=kuipr,DC=de'
    additional_users_dn: 'OU=users'
    users_filter: '(&({username_attribute}={input})(objectClass=person))'
    additional_groups_dn: 'OU=groups'
    groups_filter: '(&(member={dn})(objectClass=groupOfNames))'
    group_search_mode: 'filter'
    permit_referrals: false
    permit_unauthenticated_bind: false
    permit_feature_detection_failure: false
    user: 'CN=admin,DC=kuipr,DC=de'
    password: 'password'
    attributes:
      distinguished_name: 'distinguishedName'
      username: 'uid'
      display_name: 'displayName'
      family_name: 'sn'
      given_name: 'givenName'
      middle_name: 'middleName'
      nickname: ''
      gender: ''
      birthdate: ''
      website: 'wWWHomePage'
      profile: ''
      picture: ''
      zoneinfo: ''
      locale: ''
      phone_number: 'telephoneNumber'
      phone_extension: ''
      street_address: 'streetAddress'
      locality: 'l'
      region: 'st'
      postal_code: 'postalCode'
      country: 'c'
      mail: 'mail'
      member_of: 'memberOf'
      group_name: 'cn'
      extra:
        extra_example:
          name: ''
          multi_valued: false
          value_type: 'string'

# Access control configuration
access_control:
  default_policy: one_factor
  rules:
    - domain: "sonarr.kuipr.de"
      resources:
        - "^/api/.*$"
      policy: bypass
    - domain: "radarr.kuipr.de"
      resources:
        - "^/api/.*$"
      policy: bypass
    - domain: "*.kuipr.de"
      policy: one_factor

# Session configuration
session:
  name: authelia_session
  expiration: 3600  # seconds
  inactivity: 300   # seconds
  domain: kuipr.de
  redis:
    host: redis
    port: 6379
    database_index: 0

# Storage configuration
storage:
  local:
    path: /data/db.sqlite3

# Notification settings
notifier:
  filesystem:
    filename: /data/notification.txt

# Regulation for failed attempts
regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

# Logging configuration
log:
  level: debug

# Telemetry
telemetry:
  metrics:
    enabled: false

webauthn:
  disable: false
  enable_passkey_login: true
  display_name: 'Authelia'
  attestation_conveyance_preference: 'indirect'
  timeout: '60 seconds'
  filtering:
    permitted_aaguids: []
    prohibited_aaguids: []
    prohibit_backup_eligibility: false
  selection_criteria:
    attachment: ''
    discoverability: 'preferred'
    user_verification: 'preferred'
  metadata:
    enabled: false
    validate_trust_anchor: true
    validate_entry: true
    validate_entry_permit_zero_aaguid: false
    validate_status: true
    validate_status_permitted: []
    validate_status_prohibited:
      - 'REVOKED'
      - 'USER_KEY_PHYSICAL_COMPROMISE'
      - 'USER_KEY_REMOTE_COMPROMISE'
      - 'USER_VERIFICATION_BYPASS'
      - 'ATTESTATION_KEY_COMPROMISE'
