---
##############################################
#                                            #
#              Authelia Config               #
#                                            #
##############################################

# The host and port to listen on
server:
  host: 0.0.0.0
  port: 9091

# URL to use for redirects
server_url: "https://auth.kuipr.de"

# Default redirection URL
default_redirection_url: https://kuipr.de

# TOTP settings
totp:
  issuer: kuipr.de
  period: 30
  skew: 1

# Authentication backend
authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64

# Access control configuration
access_control:
  default_policy: 'deny'
  rules:
    # Public domains that don't require authentication
    - domain: whoami.kuipr.de
      policy: bypass
    
    # Protected domains that require authentication
    - domain: "*.kuipr.de"
      policy: one_factor

# Session configuration
session:
  name: authelia_session
  expiration: 3600  # 1 hour
  inactivity: 300   # 5 minutes
  domain: kuipr.de  # Domain to use for cookies
  redis:
    host: redis
    port: 6379
    database_index: 0

# Storage configuration
storage:
  local:
    path: /data/db.sqlite3

# Notification settings - using file output in development
# In production, use SMTP configuration
notifier:
  filesystem:
    filename: /data/notification.txt

# Regulation for failed attempts
regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

# Logging configuration
log:
  level: debug

# Telemetry
telemetry:
  metrics:
    enabled: false
