##############################################
#                                            #
#              Authelia Config               #
#                                            #
##############################################
# The host and port to listen on
server:
  host: 0.0.0.0
  port: 9091

# Default redirection URL
default_redirection_url: https://kuipr.de

# TOTP settings
totp:
  issuer: kuipr.de
  period: 30
  skew: 1

# WebAuthn settings (outside of authentication_backend)
webauthn:
  display_name: kuipr.de
  attestation_conveyance_preference: indirect
  user_verification: preferred
  timeout: 60s

# Authentication backend
authentication_backend:
  file:
    path: /config/users_database.yaml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64

# Access control configuration
access_control:
  default_policy: one_factor
  rules:
    # - domain: whoami.kuipr.de
    #   policy: bypass
    - domain: "*.kuipr.de"
      policy: one_factor

# Session configuration
session:
  name: authelia_session
  expiration: 3600  # seconds
  inactivity: 300   # seconds
  domain: kuipr.de
  redis:
    host: redis
    port: 6379
    database_index: 0
  
# HTTP header settings
# Commenting out Duo API as it's not required
# duo_api:
#   hostname: api-123456789.duosecurity.com
#   integration_key: ABCDEF
#   secret_key: 1234567890abcdefghijklmnopqrstuvwxyz

# Enable proxying of headers
server:
  use_forwarded_headers: true
  forwarded_headers_version: 2  # RFC7239 standard format

# Storage configuration
storage:
  local:
    path: /data/db.sqlite3

# Notification settings
notifier:
  filesystem:
    filename: /data/notification.txt

# Regulation for failed attempts
regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

# Logging configuration
log:
  level: debug

# Telemetry
telemetry:
  metrics:
    enabled: false

# HTTP header forwarding configuration
# Proxy headers configuration
server:
  address: tcp://0.0.0.0:9091
  tls:
    certificate: ""
    key: ""
  headers:
    read_header_timeout: 5s
    write_timeout: 10s
    idle_timeout: 120s
  enable_pprof: false
  enable_expvars: false

# Theme (optional)
theme: light
