##############################################
#                                            #
#              Authelia Config               #
#                                            #
##############################################
# The host and port to listen on
server:
  host: 0.0.0.0
  port: 9091

# Default redirection URL
default_redirection_url: https://kuipr.de

# TOTP settings
totp:
  issuer: kuipr.de
  period: 30
  skew: 1

# Authentication backend
authentication_backend:
  file:
    path: /config/users_database.yaml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64

# Access control configuration
access_control:
  default_policy: one_factor
  rules:
    - domain: "sonarr.kuipr.de/api"
      policy: bypass
    - domain: "radarr.kuipr.de/api"
      policy: bypass
    - domain: "*.kuipr.de"
      policy: one_factor

# Session configuration
session:
  name: authelia_session
  expiration: 3600  # seconds
  inactivity: 300   # seconds
  domain: kuipr.de
  redis:
    host: redis
    port: 6379
    database_index: 0

# Storage configuration
storage:
  local:
    path: /data/db.sqlite3

# Notification settings
notifier:
  filesystem:
    filename: /data/notification.txt

# Regulation for failed attempts
regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

# Logging configuration
log:
  level: debug

# Telemetry
telemetry:
  metrics:
    enabled: false
