title: NixOS Homelab Dashboard
description: My Homelab Dashboard
favicon: https://www.google.com/favicon.ico
color: slate
theme: dark # or light
headerStyle: clean
language: en
hideVersion: true
disableUpdateCheck: true
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
  provider: duckduckgo # google, duckduckgo, bing, baidu, brave or custom
layout:
  - Infrastructure:
      style: row
      columns: 4
  - Networking:
      style: row
      columns: 4
  - Media:
      style: row
      columns: 4
  - Downloads:
      style: row
      columns: 4
  - Storage & Documentation:
      style: row
      columns: 4
