# Auto-generated using compose2nix v0.3.2-pre.
{ pkgs, lib, config, ... }:

{
  sops.secrets."watchtower.env" = {
    sopsFile = ./watchtower.env;
    format = "dotenv";
    key = "";
    restartUnits = ["podman-watchtower.service"];
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."watchtower" = {
    image = "containrrr/watchtower";
    volumes = [
      "/run/podman/podman.sock:/var/run/docker.sock:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=watchtower"
      "--network=watchtower_default"
    ];
    environmentFiles = [
      "${config.sops.secrets."watchtower.env".path}"
    ];
  };
  systemd.services."podman-watchtower" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-watchtower_default.service"
    ];
    requires = [
      "podman-network-watchtower_default.service"
    ];
    partOf = [
      "podman-compose-watchtower-root.target"
    ];
    wantedBy = [
      "podman-compose-watchtower-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-watchtower_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f watchtower_default";
    };
    script = ''
      podman network inspect watchtower_default || podman network create watchtower_default
    '';
    partOf = [ "podman-compose-watchtower-root.target" ];
    wantedBy = [ "podman-compose-watchtower-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-watchtower-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
