# Auto-generated by compose2nix.

{
  pkgs,
  lib,
  config,
  ...
}:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces =
    let
      matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
    in
    {
      "${matchAll}".allowedUDPPorts = [ 53 ];
    };


  myFolders = {
    aiostreams = {
      path = "/home/ubuntu/aiostreams";
      owner = "ubuntu";
      group = "users";
      mode = "0755";
    };
  };

  sops.secrets."aiostreams.env" = {
    sopsFile = ./aio.env;
    format = "dotenv";
    key = "";
    restartUnits = [ "podman-aiostreams.service" ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."aiostreams" = {
    image = "ghcr.io/viren070/aiostreams:latest";
    volumes = [
      "/home/ubuntu/aiostreams:/app/data:rw"
    ];
    # ports = [
    #   "3000:3000/tcp"
    # ];

    environmentFiles = [
      "/run/secrets/aiostreams.env"
    ];
    log-driver = "journald";

    labels = {
      "io.containers.autoupdate" = "registry";
      "traefik.enable" = "true";
      "traefik.http.routers.aiostreams.entrypoints" = "websecure";
      "traefik.http.routers.aiostreams.middlewares" = "authelia@docker,block-metrics@docker";
      "traefik.http.routers.aiostreams.rule" = "Host(`aiostreams.kuipr.de`)";
      "traefik.http.routers.aiostreams.tls.certresolver" = "myresolver";
      "traefik.http.services.aiostreams.loadbalancer.server.port" = "3000";
      "traefik.port" = "3000";
    };
    extraOptions = [
      "--health-cmd=wget -qO- http://localhost:3000/api/v1/status"
      "--health-interval=1m0s"
      "--health-retries=5"
      "--health-start-period=10s"
      "--health-timeout=10s"
      # "--network-alias=aiostreams"
      "--network=aiostreams_default"
      "--network=container:gluetun"
    ];
  };
  systemd.services."podman-aiostreams" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-aiostreams_default.service"
    ];
    requires = [
      "podman-network-aiostreams_default.service"
    ];
    partOf = [
      "podman-compose-aiostreams-root.target"
    ];
    wantedBy = [
      "podman-compose-aiostreams-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-aiostreams_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f aiostreams_default";
    };
    script = ''
      podman network inspect aiostreams_default || podman network create aiostreams_default
    '';
    partOf = [ "podman-compose-aiostreams-root.target" ];
    wantedBy = [ "podman-compose-aiostreams-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-aiostreams-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
