{pkgs, ...}: {
  imports = [
    ./gluetun.nix
    ./torrent.nix
  ];

  systemd.services."podman-network-seedbox_default" = {
    path = [pkgs.podman];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f seedbox_default";
    };
    script = ''
      podman network inspect seedbox_default || podman network create seedbox_default
    '';
    partOf = ["podman-compose-seedbox-root.target"];
    wantedBy = ["podman-compose-seedbox-root.target"];
  };

  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-seedbox-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
