# Auto-generated using compose2nix v0.3.2-pre.
{
  pkgs,
  lib,
  config,
  ...
}: {
  myFolders = {
    jellyfin = {
      path = "/home/ubuntu/jellyfin/{cache,config}";
      owner = "ubuntu";
      group = "users";
      mode = "0755";
    };
  };



  # SMB credentials managed by sops; fill values in `stacks/navidrome/smbcredentials` and encrypt with sops
  sops.secrets."navidrome-smbcredentials" = {
    sopsFile = ./smbcredentials.txt;
    format = "binary";
    owner = "root";
    group = "root";
    mode = "0600";
    key = "";
    restartUnits = ["smb-mount-music.service"];
  };

  fileSystems."/mnt/share" = {
    device = "//192.168.0.58/data";
    fsType = "cifs";
    options = let
      # this line prevents hanging on network split
      automount_opts = "x-systemd.automount,noauto,x-systemd.idle-timeout=60,x-systemd.device-timeout=5s,x-systemd.mount-timeout=5s";
    in ["${automount_opts},credentials=${config.sops.secrets."navidrome-smbcredentials".path}"];
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll =
      if !config.networking.nftables.enable
      then "podman+"
      else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [53];
  };

  # Containers
  virtualisation.oci-containers.containers."jellyfin" = {
    image = "docker.io/jellyfin/jellyfin";
    environment = {
      "JELLYFIN_PublishedServerUrl" = "https://jelly.kuipr.de";
    };
    volumes = [
      "/mnt/share/Music:/music:rw"
      "/home/ubuntu/jellyfin/cache:/cache:rw"
      "/home/ubuntu/jellyfin/config:/config:rw"
      "${./system.xml}:/config/config/system.xml:rw"
      "${./network.xml}:/config/config/network.xml:ro"
      "${./branding.xml}:/config/config/branding.xml:ro"
    ];
    labels = {
      "io.containers.autoupdate" = "registry";
      "traefik.enable" = "true";
      # "traefik.http.routers.jellyfin.entrypoints" = "websecure";
      "traefik.http.routers.jellyfin.entrypoints" = "anubis";
      "traefik.http.routers.jellyfin.rule" = "Host(`jelly.kuipr.de`)";
      # "traefik.http.routers.jellyfin.tls.certresolver" = "myresolver";
      "traefik.http.services.jellyfin.loadbalancer.server.port" = "8096";
      # "traefik.http.routers.jellyfin.middlewares" = "block-metrics@docker";
    };
    user = "0:0";
    log-driver = "journald";
    extraOptions = [
      "--network-alias=jellyfin"
      "--network=jellyfin_default"
      "--network=proxy"
    ];
  };
  systemd.services."podman-jellyfin" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-jellyfin_default.service"
    ];
    requires = [
      "podman-network-jellyfin_default.service"
    ];
    partOf = [
      "podman-compose-jellyfin-root.target"
    ];
    wantedBy = [
      "podman-compose-jellyfin-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-jellyfin_default" = {
    path = [pkgs.podman];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f jellyfin_default";
    };
    script = ''
      podman network inspect jellyfin_default || podman network create jellyfin_default
    '';
    partOf = ["podman-compose-jellyfin-root.target"];
    wantedBy = ["podman-compose-jellyfin-root.target"];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-jellyfin-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
