# Auto-generated using compose2nix v0.3.2-pre.
{ pkgs, lib, config, ... }:

{
  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."uptime-kuma-uptime-kuma" = {
    image = "louislam/uptime-kuma:1";
    volumes = [
      "/home/ubuntu/kuma:/app/data:rw"
      "/var/run/docker.sock:/var/run/docker.sock:rw"
    ];
    labels = {
      "traefik.docker.network" = "proxy";
      "traefik.enable" = "true";
      "traefik.http.routers.uptime-kuma.entrypoints" = "websecure";
      "traefik.http.routers.uptime-kuma.middlewares" = "authentik@docker";
      "traefik.http.routers.uptime-kuma.rule" = "Host(`uptime.kuipr.de`)";
      "traefik.http.routers.uptime-kuma.tls.certresolver" = "myresolver";
      "traefik.http.services.uptime-kuma.loadbalancer.server.port" = "3001";
      "traefik.port" = "3001";
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=uptime-kuma"
      "--network=proxy"
      "--network=uptime-kuma_default"
    ];
  };
  systemd.services."podman-uptime-kuma-uptime-kuma" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-uptime-kuma_default.service"
    ];
    requires = [
      "podman-network-uptime-kuma_default.service"
    ];
    partOf = [
      "podman-compose-uptime-kuma-root.target"
    ];
    wantedBy = [
      "podman-compose-uptime-kuma-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-uptime-kuma_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f uptime-kuma_default";
    };
    script = ''
      podman network inspect uptime-kuma_default || podman network create uptime-kuma_default
    '';
    partOf = [ "podman-compose-uptime-kuma-root.target" ];
    wantedBy = [ "podman-compose-uptime-kuma-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-uptime-kuma-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
