http:
  middlewares:
    internal-only:
      ipWhiteList:
        sourceRange:
          - "127.0.0.0/8"
          - "10.0.0.0/8"
          - "172.16.0.0/12"
          - "192.168.0.0/16"

    # Add request tracing headers
    add-request-id:
      headers:
        customRequestHeaders:
          X-Request-ID: "{{ .TraefikRequestID }}"
          X-Forwarded-By: "traefik"

    # Middleware to log real IP information
    real-ip-headers:
      headers:
        customRequestHeaders:
          X-Debug-Client-IP: "{{ .ClientIP }}"
          X-Debug-Remote-Addr: "{{ .RemoteAddr }}"

  routers:
    metrics-blocker:
      rule: "PathPrefix(`/metrics`)"
      middlewares:
        - "internal-only"
      priority: 1000
      entryPoints:
        - websecure
        - web
        - anubis
