# Auto-generated using compose2nix v0.3.2-pre.
{ pkgs, lib, config, ... }:

{

  myFolders = {
    organizr = {
      path = "/home/ubuntu/organizr";
      owner = "ubuntu";
      group = "users";
      mode = "0755";
    };
  };


  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."organizr" = {
    image = "organizr/organizr:latest";
    volumes = [
      "/home/ubuntu/organizr:/config:rw"
    ];
    labels = {
      "traefik.enable" = "true";
      "traefik.http.routers.organizr.entrypoints" = "websecure";
      "traefik.http.routers.organizr.middlewares" = "authelia@docker";
      "traefik.http.routers.organizr.rule" = "Host(`organizr.kuipr.de`)";
      "traefik.http.routers.organizr.tls.certresolver" = "myresolver";
      "traefik.http.services.organizr.loadbalancer.server.port" = "9696";
    };
    log-driver = "journald";
    extraOptions = [
      "--hostname=organizr"
      "--network-alias=organizr"
      "--network=organizr_default"
      "--network=proxy"
    ];
  };
  systemd.services."podman-organizr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-organizr_default.service"
    ];
    requires = [
      "podman-network-organizr_default.service"
    ];
    partOf = [
      "podman-compose-organizr-root.target"
    ];
    wantedBy = [
      "podman-compose-organizr-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-organizr_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f organizr_default";
    };
    script = ''
      podman network inspect organizr_default || podman network create organizr_default
    '';
    partOf = [ "podman-compose-organizr-root.target" ];
    wantedBy = [ "podman-compose-organizr-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-organizr-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
