# Auto-generated using compose2nix v0.3.2-pre.
{
  pkgs,
  lib,
  config,
  ...
}: {
  # Runtime
  sops.secrets = {
    "anubis.env" = {
      sopsFile = ./anubis.env;
      format = "dotenv";
      key = "";
      restartUnits = ["podman-anubis-default.service"];
    };
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll =
      if !config.networking.nftables.enable
      then "podman+"
      else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [53];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."anubis" = {
    image = "ghcr.io/techarohq/anubis:latest";
    environmentFiles = [
      "${config.sops.secrets."anubis.env".path}"
    ];
    # ports = [
    #   "8923:8923/tcp"
    # ];
    labels = {
      "traefik.docker.network" = "proxy"; # Telling Traefik which network to use
      "traefik.http.routers.anubis.priority" = "1"; # Setting Anubis to the lowest priority, so it only takes the slack
      "traefik.http.routers.anubis.rule" = "PathRegexp(`.*`)"; # Wildcard match every path
      "traefik.http.routers.anubis.entrypoints" = "websecure"; # Listen on HTTPS
      "traefik.http.services.anubis.loadbalancer.server.port" = "8080"; # Telling Traefik to which port it should route requests
      "traefik.http.routers.anubis.service" = "anubis"; # Telling Traefik to use the above specified port
      "traefik.http.routers.anubis.tls.certresolver" = "le"; # Telling Traefik to resolve a Cert for Anubis
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=anubis"
      "--network=proxy"
    ];
  };
  systemd.services."podman-anubis" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-anubis-root.target"
    ];
    wantedBy = [
      "podman-compose-anubis-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-anubis-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
