{lib, ...}: {
  sops.secrets."gluetun.env" = {
    sopsFile = ./gluetun.env;
    format = "dotenv";
    key = "";
    restartUnits = ["podman-gluetun.service"];
  };

  virtualisation.oci-containers.containers."gluetun" = {
    image = "qmcgaw/gluetun";
    log-driver = "journald";
    environmentFiles = [
      "/run/secrets/gluetun.env"
    ];
    extraOptions = [
      "--cap-add=NET_ADMIN"
      "--device=/dev/net/tun:/dev/net/tun:rwm"
      "--health-cmd=[\"wget\", \"-qO-\", \"https://ipinfo.io/ip\"]"
      "--health-interval=30s"
      "--health-retries=3"
      "--health-start-period=10s"
      "--health-timeout=10s"
      "--network-alias=gluetun"
      "--network=proxy"
    ];
    ports = [
      "8080:8080"
      "47594/tcp"
      "47594/udp"
    ];
  };
  systemd.services."podman-gluetun" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-gluetun-root.target"
    ];
    wantedBy = [
      "podman-compose-gluetun-root.target"
    ];
  };


  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-gluetun-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
